### ISSUE TITLE
Missing AuthResponse Variant

### ISSUE THREAD

**Issue by akbog** [andrusha/snowflake-rs#17]
First off! Big shoutout on this open source crate that lets you query the snowflake api from Rust :) Really appreciate it!

Stumbled upon an unfortunate AuthResponse decoding error:

```
error decoding response body: data did not match any variant of untagged enum AuthResponse
```

We were able to reproduce this by initializing the snowflake_api client with a Role that the user has not been granted. It's very hard to debug this if the crate throws an error as such! In this case, consider either serializing the snowflake api response as a string and returning that as an "UnknownError" etc. or handling the type

**Comment by andrusha** [comment]
@akbog you can run the code with env logger at trace level and it'll output all the raw responses to the console, which might help with the debugging:

```
RUST_LOG=TRACE cargo run --example run_sql -- --sql "select * from TEST.TEST" ...
```

**Comment by akbog** [comment]
Thanks so much for the fix and advice! :)
