### ISSUE TITLE
Release new version 0.3.1 of this crate

### ISSUE THREAD

**Issue by xmakro** [andrusha/snowflake-rs#6]

**Comment by tbaums** [comment]
cc @knowthen @josephrosenberg @dmzmk @andrusha for visibility. 

Can we get a version bump for the crate now that we have @xmakro 's awesome PR merged in?

**Comment by andrusha** [comment]
Hey, since you merge PRs, you can make a git tag and manually trigger related Publish workflow. It’s all accessible through UI. The version was bumped in the merged PR iirc.

**Comment by dmzmk** [comment]
snowflake-api with version v0.3.1 published on crates
